// module Data.Function, generated by purescript-tsd-gen 0.3.0.0
export const flip: <a, b, c>(_: (_: a) => (_: b) => c) => (_: b) => (_: a) => c;
declare const $$const: <a, b>(_: a) => (_: b) => a;
export const apply: <a, b>(_: (_: a) => b) => (_: a) => b;
export const applyFlipped: <a, b>(_: a) => (_: (_: a) => b) => b;
export const applyN: <a>(_: (_: a) => a) => (_: number) => (_: a) => a;
export const on: <a, b, c>(_: (_: b) => (_: b) => c) => (_: (_: a) => b) => (_: a) => (_: a) => c;
export /*value*/ { $$const as const };
