// module Data.Unit, generated by purescript-tsd-gen 0.3.0.0
import * as Data_Show from "../Data.Show";
export type /*builtin*/ Unit = { "$$pursType"?: "Data.Unit.Unit" };
export const unit: Unit;
export const /*instance*/ showUnit: Data_Show.Show< Unit >;
export {};
