// module Type.Data.RowList, generated by purescript-tsd-gen 0.3.0.0
// type RLProxy :: Prim.RowList.RowList -> Type : unsupported kind
// unrecognized data constructor: RLProxy kind: Prim.RowList.RowList -> Type
export {};
