// module Data.Ordering, generated by purescript-tsd-gen 0.3.0.0
import * as Data_Eq from "../Data.Eq";
import * as Data_Semigroup from "../Data.Semigroup";
import * as Data_Show from "../Data.Show";
export type /*data*/ Ordering = Ordering$$LT | Ordering$$GT | Ordering$$EQ;
interface Ordering$$LT {
    "$$pursType": "Data.Ordering.Ordering";
    "$$pursTag": "LT";
}
export const /*data ctor*/ LT: { value: Ordering; new (): Ordering$$LT };
interface Ordering$$GT {
    "$$pursType": "Data.Ordering.Ordering";
    "$$pursTag": "GT";
}
export const /*data ctor*/ GT: { value: Ordering; new (): Ordering$$GT };
interface Ordering$$EQ {
    "$$pursType": "Data.Ordering.Ordering";
    "$$pursTag": "EQ";
}
export const /*data ctor*/ EQ: { value: Ordering; new (): Ordering$$EQ };
export const invert: (_: Ordering) => Ordering;
export const /*instance*/ eqOrdering: Data_Eq.Eq< Ordering >;
export const /*instance*/ semigroupOrdering: Data_Semigroup.Semigroup< Ordering >;
export const /*instance*/ showOrdering: Data_Show.Show< Ordering >;
export {};
