// module Data.Void, generated by purescript-tsd-gen 0.3.0.0
import * as Data_Show from "../Data.Show";
export type /*data*/ Void = { "$$pursType": "Data.Void.Void"; "$$pursTag": "Void"; "$$abstractMarker": never };
export const absurd: <a>(_: Void) => a;
export const /*instance*/ showVoid: Data_Show.Show< Void >;
export {};
