// module Record.Unsafe, generated by purescript-tsd-gen 0.3.0.0
export const unsafeHas: (_: string) => (_: {}) => boolean;
export const unsafeGet: <a>(_: string) => (_: {}) => a;
export const unsafeSet: <a>(_: string) => (_: a) => (_: {}) => {};
export const unsafeDelete: (_: string) => (_: {}) => {};
export {};
