// module Data.Bounded, generated by purescript-tsd-gen 0.3.0.0
import * as Data_Ord from "../Data.Ord";
import * as Data_Ordering from "../Data.Ordering";
import * as Data_Unit from "../Data.Unit";
export type /*synonym*/ Bounded<a> = { top: a; bottom: a; Ord0: (_: {}) => Data_Ord.Ord< a > };
export const bottom: <a>(_: Bounded< a >) => a;
export const top: <a>(_: Bounded< a >) => a;
export const /*instance*/ boundedBoolean: Bounded< boolean >;
export const /*instance*/ boundedInt: Bounded< number >;
export const /*instance*/ boundedChar: Bounded< string >;
export const /*instance*/ boundedOrdering: Bounded< Data_Ordering.Ordering >;
export const /*instance*/ boundedUnit: Bounded< Data_Unit.Unit >;
export const /*instance*/ boundedNumber: Bounded< number >;
export {};
