// module Data.Field, generated by purescript-tsd-gen 0.3.0.0
import * as Data_DivisionRing from "../Data.DivisionRing";
import * as Data_EuclideanRing from "../Data.EuclideanRing";
export type /*synonym*/ Field<a> = { EuclideanRing0: (_: {}) => Data_EuclideanRing.EuclideanRing< a >; DivisionRing1: (_: {}) => Data_DivisionRing.DivisionRing< a > };
export const /*instance*/ field: <a>(_: Data_EuclideanRing.EuclideanRing< a >) => (_: Data_DivisionRing.DivisionRing< a >) => Field< a >;
export {};
