// module Data.DivisionRing, generated by purescript-tsd-gen 0.3.0.0
import * as Data_Ring from "../Data.Ring";
export type /*synonym*/ DivisionRing<a> = { recip: (_: a) => a; Ring0: (_: {}) => Data_Ring.Ring< a > };
export const recip: <a>(_: DivisionRing< a >) => (_: a) => a;
export const leftDiv: <a>(_: DivisionRing< a >) => (_: a) => (_: a) => a;
export const rightDiv: <a>(_: DivisionRing< a >) => (_: a) => (_: a) => a;
export const /*instance*/ divisionringNumber: DivisionRing< number >;
export {};
